- hosts: all
  vars_files:
  - http_var.yml        
  tasks:
  - file:
      state: directory
      path: "{{ dvd_dir }}"    

  - mount:
      src: "/dev/cdrom"
      path: "{{ dvd_dir }}"
      state: mounted
      fstype: "iso9660"

  - yum_repository:
      baseurl: "{{ dvd_dir }}/AppStream"
      name: "mydvd1"     
      description: "my yum dvd1 for package"
      gpgcheck: no

  - yum_repository:
      baseurl: "{{ dvd_dir }}/BaseOS"
      name: "mydvd2"     
      description: "my yum dvd2 for package"
      gpgcheck: no 

  - package:
      name: "httpd"
      state: present

  - file:
      state: directory
      path: "{{ doc_root }}"

  - template:
      dest: "/etc/httpd/conf.d/httpd.conf"
      src: "httpd.conf"
    register: temp

  - debug:
      var: temp    

  - copy:
      dest: "{{ doc_root }}/index.html"    
      content: "welcome to my new site!!!\n" 

  handlers:
  - service: 
      name: "httpd"
      state: restarted
      enabled: yes

  - firewalld:
      port: "{{ http_port }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes
      
